# Generated by Django 5.2.7 on 2025-10-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='session_id',
            field=models.CharField(blank=True, help_text='Session identifier for tracking attempts', max_length=100),
        ),
    ]
