# Generated by Django 5.2.7 on 2025-10-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0002_studentanswer_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='time_taken_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Time taken for this attempt in seconds'),
        ),
    ]
