# Generated by Django 5.2.7 on 2025-10-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0003_studentanswer_time_taken_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='session_id',
            field=models.CharField(blank=True, default='', help_text='Session identifier for tracking attempts', max_length=100),
        ),
    ]
