# Generated by Django 5.2.7 on 2025-11-02 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0005_update_student_answer_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicFactsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session identifier for tracking attempts', max_length=100)),
                ('score', models.PositiveIntegerField(help_text='Number of correct answers')),
                ('total_points', models.PositiveIntegerField(help_text='Total possible points')),
                ('time_taken_seconds', models.PositiveIntegerField(help_text='Time taken for this attempt in seconds')),
                ('points', models.DecimalField(decimal_places=2, help_text='Calculated points based on score, time, and percentage', max_digits=10)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_facts_results', to='maths.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_facts_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['student', 'level'], name='maths_basic_student_e1bd97_idx'), models.Index(fields=['student', 'level', 'session_id'], name='maths_basic_student_8dd087_idx')],
            },
        ),
    ]
