# Generated by Django 5.2.7 on 2025-11-05 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0007_customuser_country_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_total_seconds', models.PositiveIntegerField(default=0, help_text='Total seconds spent today')),
                ('weekly_total_seconds', models.PositiveIntegerField(default=0, help_text='Total seconds spent this week')),
                ('last_reset_date', models.DateField(auto_now=True, help_text='Last date when daily time was reset')),
                ('last_reset_week', models.IntegerField(default=0, help_text='ISO week number of last weekly reset')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last time activity was recorded')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
    ]
