# Generated by Django 5.2.7 on 2025-11-07 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0008_timelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Topic this question belongs to (e.g., BODMAS/PEMDAS, Measurements, Fractions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='maths.topic'),
        ),
    ]
