# Generated by Django 5.2.7 on 2025-11-13 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0009_question_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicLevelStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_points', models.DecimalField(decimal_places=2, default=0, help_text='Average points across all students', max_digits=10)),
                ('sigma', models.DecimalField(decimal_places=2, default=0, help_text='Standard deviation (sigma)', max_digits=10)),
                ('student_count', models.PositiveIntegerField(default=0, help_text='Number of students who have completed this topic-level')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last time statistics were calculated')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_statistics', to='maths.level')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_statistics', to='maths.topic')),
            ],
            options={
                'ordering': ['level__level_number', 'topic__name'],
                'indexes': [models.Index(fields=['level', 'topic'], name='maths_topic_level_i_267d9e_idx')],
                'unique_together': {('level', 'topic')},
            },
        ),
    ]
