# Generated by Django 5.2.7 on 2025-11-15 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maths', '0010_topiclevelstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFinalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session identifier for this attempt', max_length=100)),
                ('attempt_number', models.PositiveIntegerField(help_text='Attempt number for this student-topic-level combination (increments for each new attempt)')),
                ('points_earned', models.DecimalField(decimal_places=2, help_text='Final points earned for this attempt', max_digits=10)),
                ('last_updated_time', models.DateTimeField(auto_now=True, help_text='Last time this record was updated')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_answers', to='maths.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_answers', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_answers', to='maths.topic')),
            ],
            options={
                'ordering': ['-last_updated_time'],
                'indexes': [models.Index(fields=['student', 'topic', 'level'], name='maths_stude_student_ad30a8_idx'), models.Index(fields=['student', 'topic', 'level', 'attempt_number'], name='maths_stude_student_2e8b01_idx')],
                'unique_together': {('student', 'session_id')},
            },
        ),
    ]
